src/mvc/BuracoNasLetras.App/ViewModels/ErrorViewModel.cs
using System;

namespace BuracoNasLetras.App.ViewModels
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/mvc/BuracoNasLetras.App/ViewModels/PapelViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace BuracoNasLetras.App.ViewModels
{
    public class PapelViewModel
    {
        [Key]
        public Guid Id { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        public string Texto { get; set; }

        public int Tamanho { get; set; }
        public int TotalDePalavras { get; set; }
        public int TotalDeBuracos { get; set; }
    }
}

src/mvc/BuracoNasLetras.App/Controllers/HomeController.cs
using BuracoNasLetras.App.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace BuracoNasLetras.App.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/mvc/BuracoNasLetras.App/Controllers/PapeisController.cs
using AutoMapper;
using BuracoNasLetras.App.ViewModels;
using BuracoNasLetras.Business.Interfaces;
using BuracoNasLetras.Business.Models;
using BuracoNasLetras.ConsoleApp.Extensions;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace BuracoNasLetras.App.Controllers
{
    public class PapeisController : Controller
    {
        protected readonly IPapelRepository _papelRepository;
        protected readonly IMapper _mapper;
        protected readonly QuantidadeBuracosTexto _quantidadeBuracosTexto;

        public PapeisController(IPapelRepository papelRepository, IMapper mapper, QuantidadeBuracosTexto quantidadeBuracosTexto)
        {
            _papelRepository = papelRepository;
            _mapper = mapper;
            _quantidadeBuracosTexto = quantidadeBuracosTexto;
        }

        public async Task<IActionResult> Index()
        {
            return View(_mapper.Map<IEnumerable<PapelViewModel>>(await _papelRepository.ObterTodos()));
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PapelViewModel papelViewModel)
        {
            if (!ModelState.IsValid) return View(papelViewModel);

            var papel = _mapper.Map<Papel>(papelViewModel);

            var papelAtualizado = PopularInformacoesPapel(papel);

            await _papelRepository.Adicionar(papelAtualizado);

            return RedirectToAction(nameof(Index));
        }

        public Papel PopularInformacoesPapel(Papel papel)
        {
            papel.Tamanho = papel.Texto.Length;
            papel.TotalDePalavras = papel.Texto.Replace(" ", "").Length;
            papel.TotalDeBuracos = _quantidadeBuracosTexto.QuantidadeDeBuracos(papel.Texto);

            return papel;
        }
    }
}

src/mvc/BuracoNasLetras.App/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Buraco Nas Letras</h1>
    <p>Entre em contato comigo pelo e-mail <a href="mailto:contato@yurisiman.com.br">contato@yurisiman.com.br</a></p>
</div>

src/mvc/BuracoNasLetras.App/Views/Papeis/Create.cshtml
@model BuracoNasLetras.App.ViewModels.PapelViewModel

@{
    ViewData["Title"] = "Digitar Novo Texto";
}

<h1>@ViewData["Title"]</h1>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Texto" class="control-label"></label>
                <input asp-for="Texto" class="form-control" />
                <span asp-validation-for="Texto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Adicionar Texto" class="btn btn-primary" />
                <a class="btn btn-info" asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/mvc/BuracoNasLetras.App/Views/Papeis/Index.cshtml
@model IEnumerable<BuracoNasLetras.App.ViewModels.PapelViewModel>

@{
    ViewData["Title"] = "Informações dos Textos Inseridos";
}

<h1>@ViewData["Title"]</h1>
<hr />
<p>
    <a class="btn btn-info" asp-action="Create">Inserir Novo Texto</a>
</p>
<table class="table table-hover">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Texto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tamanho)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalDePalavras)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalDeBuracos)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Texto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tamanho)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalDePalavras)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalDeBuracos)
            </td>
            <td>
            </td>
        </tr>
        }
    </tbody>
</table>

src/mvc/BuracoNasLetras.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BuracoNasLetras.App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BuracoNasLetras.App</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Papeis" asp-action="Index">Informar Texto</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - BuracoNasLetras.App - <a href="mailto:contato@yurisiman.com.br">contato@yurisiman.com.br</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>